import { pipeline, env } from "https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.7.2";
env.allowLocalModels=false; env.useBrowserCache=true;
const $=id=>document.getElementById(id); const src=$("src"),out=$("out"),file=$("file"),status=$("status"),bar=$("progress"),btn=$("translate"),dl=$("download"),copy=$("copy"),errorBox=$("error"); let translator=null,busy=false;
function progress(n,t,c=""){bar.style.width=Math.max(0,Math.min(100,n))+"%";status.textContent=t;status.className=c} function clearError(){errorBox.textContent=""}
function parseSRT(text){text=text.replace(/^\uFEFF/,"").replace(/\r/g,"").trim();return text.split(/\n{2,}/).map(block=>{const lines=block.split("\n"),ti=lines.findIndex(x=>x.includes("-->"));if(ti<0)return null;const body=lines.slice(ti+1).join(" ").replace(/\s+/g," ").trim();return body?{head:lines.slice(0,ti),time:lines[ti].trim(),text:body}:null}).filter(Boolean)}
function makeSRT(a){return a.map((b,i)=>{const h=b.head.length?b.head.join("\n")+"\n":String(i+1)+"\n";return h+b.time+"\n"+b.translated}).join("\n\n")}
async function loadModel(){const model="Xenova/nllb-200-distilled-600M";progress(1,"Memulai mesin AI...","status-working");const pipe=await pipeline("translation",model,{device:"wasm",dtype:"q8",progress_callback:d=>{if(typeof d?.progress==="number")progress(Math.round(d.progress),`Mengunduh model: ${Math.round(d.progress)}%`,"status-working")}});progress(100,"Model siap. Mulai terjemahan...","status-ready");return pipe}
async function batchTranslate(texts){try{const r=await translator(texts,{src_lang:"jpn_Jpan",tgt_lang:"ind_Latn",batch_size:Math.min(8,texts.length)});const a=Array.isArray(r)?r.map(x=>(x?.translation_text||"").trim()):[];if(a.length===texts.length)return a}catch(e){console.warn("Batch gagal, fallback:",e)}const a=[];for(const t of texts){const r=await translator(t,{src_lang:"jpn_Jpan",tgt_lang:"ind_Latn"});a.push((Array.isArray(r)?r[0]?.translation_text:r?.translation_text||"").trim())}return a}
async function translateAll(text){const blocks=parseSRT(text);if(!blocks.length)throw Error("Format subtitle tidak dikenali. Pastikan file adalah SRT.");const result=[];const size=8;for(let i=0;i<blocks.length;i+=size){const batch=blocks.slice(i,i+size);progress(Math.round(i/blocks.length*100),`Menerjemahkan ${i+1}-${Math.min(i+size,blocks.length)} dari ${blocks.length}...`,"status-working");const tr=await batchTranslate(batch.map(b=>b.text));batch.forEach((b,j)=>result.push({...b,translated:tr[j]||""}));out.value=makeSRT(result)}progress(100,"Selesai. Semua subtitle sudah diterjemahkan.","status-ready");return result}
btn.addEventListener("click",async()=>{if(busy)return;clearError();if(!src.value.trim()){errorBox.textContent="Pilih file SRT atau tempel subtitle terlebih dahulu.";return}busy=true;btn.disabled=true;try{if(!translator){btn.textContent="Memuat model...";translator=await loadModel();btn.textContent="Terjemahkan SRT"}out.value=makeSRT(await translateAll(src.value.trim()));dl.disabled=false;copy.disabled=false;btn.textContent="Terjemahkan Lagi"}catch(e){console.error(e);errorBox.textContent="Gagal: "+(e?.message||e);status.textContent="Terjadi kesalahan."}finally{busy=false;btn.disabled=false}});
file.addEventListener("change",async()=>{const f=file.files?.[0];if(!f)return;$("filename").textContent=f.name;src.value=await f.text();clearError()}); $("example").addEventListener("click",()=>{src.value=`1\n00:00:01,000 --> 00:00:03,000\nこんにちは、元気ですか？\n\n2\n00:00:04,000 --> 00:00:06,000\n今日はいい天気ですね。`;$("filename").textContent="Contoh.srt";clearError()}); $("clear").addEventListener("click",()=>{src.value="";out.value="";dl.disabled=true;copy.disabled=true;$("filename").textContent="Belum ada file";clearError()}); copy.addEventListener("click",async()=>{if(!out.value)return;try{await navigator.clipboard.writeText(out.value);copy.textContent="Tersalin ✓";setTimeout(()=>copy.textContent="Salin Hasil",1200)}catch{errorBox.textContent="Gagal menyalin. Silakan tekan lama pada hasil dan pilih Salin."}}); dl.addEventListener("click",()=>{if(!out.value)return;const u=URL.createObjectURL(new Blob([out.value],{type:"text/plain;charset=utf-8"})),a=document.createElement("a");a.href=u;a.download="translated-id.srt";a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)});
